Fix PE-D issues
AY2021S1-CS2103T-W15-2/tp pull request #201
Opened 2020-11-02 11:33 UTC by hogantan

Resolves:
* #191 
* #183 
* #178 
* #166

2020-11-03 13:36 UTC, StopTakingAllTheNames requested changes
Does `Exam` not have any tests? This has a lot of changes and a lot of functional code, it would be great to have test cases for these methods.

2020-11-04 06:48 UTC, hogantan commented
Added the relevant tests for exam and score. My bad for missing them out. Thanks for the reminder!

2020-11-04 07:02 UTC, StopTakingAllTheNames approved these changes

2020-11-04 07:02 UTC, StopTakingAllTheNames commented
Looks great

2020-11-04 07:02 UTC, merged